// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bigrid.proto
// Protobuf Java Version: 4.31.1

package org.swarmwalker.messages;

/**
 * Protobuf type {@code org.swarmwalker.messages.BiGrid}
 */
@com.google.protobuf.Generated
public final class BiGrid extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:org.swarmwalker.messages.BiGrid)
        BiGridOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      BiGrid.class.getName());
  }
  // Use BiGrid.newBuilder() to construct.
  private BiGrid(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private BiGrid() {
    items_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.swarmwalker.messages.Bigrid.internal_static_org_swarmwalker_messages_BiGrid_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.swarmwalker.messages.Bigrid.internal_static_org_swarmwalker_messages_BiGrid_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.swarmwalker.messages.BiGrid.class, org.swarmwalker.messages.BiGrid.Builder.class);
  }

  public static final int ITEMS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<org.swarmwalker.messages.Cell> items_;
  /**
   * <code>repeated .org.swarmwalker.messages.Cell items = 1;</code>
   */
  @Override
  public java.util.List<org.swarmwalker.messages.Cell> getItemsList() {
    return items_;
  }
  /**
   * <code>repeated .org.swarmwalker.messages.Cell items = 1;</code>
   */
  @Override
  public java.util.List<? extends org.swarmwalker.messages.CellOrBuilder> 
      getItemsOrBuilderList() {
    return items_;
  }
  /**
   * <code>repeated .org.swarmwalker.messages.Cell items = 1;</code>
   */
  @Override
  public int getItemsCount() {
    return items_.size();
  }
  /**
   * <code>repeated .org.swarmwalker.messages.Cell items = 1;</code>
   */
  @Override
  public org.swarmwalker.messages.Cell getItems(int index) {
    return items_.get(index);
  }
  /**
   * <code>repeated .org.swarmwalker.messages.Cell items = 1;</code>
   */
  @Override
  public org.swarmwalker.messages.CellOrBuilder getItemsOrBuilder(
      int index) {
    return items_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < items_.size(); i++) {
      output.writeMessage(1, items_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < items_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, items_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.swarmwalker.messages.BiGrid)) {
      return super.equals(obj);
    }
    org.swarmwalker.messages.BiGrid other = (org.swarmwalker.messages.BiGrid) obj;

    if (!getItemsList()
        .equals(other.getItemsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getItemsCount() > 0) {
      hash = (37 * hash) + ITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getItemsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.swarmwalker.messages.BiGrid parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.swarmwalker.messages.BiGrid parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.swarmwalker.messages.BiGrid parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.swarmwalker.messages.BiGrid parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.swarmwalker.messages.BiGrid parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.swarmwalker.messages.BiGrid parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.swarmwalker.messages.BiGrid parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.swarmwalker.messages.BiGrid parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.swarmwalker.messages.BiGrid parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.swarmwalker.messages.BiGrid parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.swarmwalker.messages.BiGrid parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.swarmwalker.messages.BiGrid parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.swarmwalker.messages.BiGrid prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.swarmwalker.messages.BiGrid}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.swarmwalker.messages.BiGrid)
      BiGridOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.swarmwalker.messages.Bigrid.internal_static_org_swarmwalker_messages_BiGrid_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.swarmwalker.messages.Bigrid.internal_static_org_swarmwalker_messages_BiGrid_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.swarmwalker.messages.BiGrid.class, org.swarmwalker.messages.BiGrid.Builder.class);
    }

    // Construct using org.swarmwalker.messages.BiGrid.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
      } else {
        items_ = null;
        itemsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.swarmwalker.messages.Bigrid.internal_static_org_swarmwalker_messages_BiGrid_descriptor;
    }

    @Override
    public org.swarmwalker.messages.BiGrid getDefaultInstanceForType() {
      return org.swarmwalker.messages.BiGrid.getDefaultInstance();
    }

    @Override
    public org.swarmwalker.messages.BiGrid build() {
      org.swarmwalker.messages.BiGrid result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public org.swarmwalker.messages.BiGrid buildPartial() {
      org.swarmwalker.messages.BiGrid result = new org.swarmwalker.messages.BiGrid(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.swarmwalker.messages.BiGrid result) {
      if (itemsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          items_ = java.util.Collections.unmodifiableList(items_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.items_ = items_;
      } else {
        result.items_ = itemsBuilder_.build();
      }
    }

    private void buildPartial0(org.swarmwalker.messages.BiGrid result) {
      int from_bitField0_ = bitField0_;
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.swarmwalker.messages.BiGrid) {
        return mergeFrom((org.swarmwalker.messages.BiGrid)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.swarmwalker.messages.BiGrid other) {
      if (other == org.swarmwalker.messages.BiGrid.getDefaultInstance()) return this;
      if (itemsBuilder_ == null) {
        if (!other.items_.isEmpty()) {
          if (items_.isEmpty()) {
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureItemsIsMutable();
            items_.addAll(other.items_);
          }
          onChanged();
        }
      } else {
        if (!other.items_.isEmpty()) {
          if (itemsBuilder_.isEmpty()) {
            itemsBuilder_.dispose();
            itemsBuilder_ = null;
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000001);
            itemsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetItemsFieldBuilder() : null;
          } else {
            itemsBuilder_.addAllMessages(other.items_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.swarmwalker.messages.Cell m =
                  input.readMessage(
                      org.swarmwalker.messages.Cell.parser(),
                      extensionRegistry);
              if (itemsBuilder_ == null) {
                ensureItemsIsMutable();
                items_.add(m);
              } else {
                itemsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<org.swarmwalker.messages.Cell> items_ =
      java.util.Collections.emptyList();
    private void ensureItemsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        items_ = new java.util.ArrayList<org.swarmwalker.messages.Cell>(items_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        org.swarmwalker.messages.Cell, org.swarmwalker.messages.Cell.Builder, org.swarmwalker.messages.CellOrBuilder> itemsBuilder_;

    /**
     * <code>repeated .org.swarmwalker.messages.Cell items = 1;</code>
     */
    public java.util.List<org.swarmwalker.messages.Cell> getItemsList() {
      if (itemsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(items_);
      } else {
        return itemsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .org.swarmwalker.messages.Cell items = 1;</code>
     */
    public int getItemsCount() {
      if (itemsBuilder_ == null) {
        return items_.size();
      } else {
        return itemsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .org.swarmwalker.messages.Cell items = 1;</code>
     */
    public org.swarmwalker.messages.Cell getItems(int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);
      } else {
        return itemsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .org.swarmwalker.messages.Cell items = 1;</code>
     */
    public Builder setItems(
        int index, org.swarmwalker.messages.Cell value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.set(index, value);
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.swarmwalker.messages.Cell items = 1;</code>
     */
    public Builder setItems(
        int index, org.swarmwalker.messages.Cell.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.set(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.swarmwalker.messages.Cell items = 1;</code>
     */
    public Builder addItems(org.swarmwalker.messages.Cell value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .org.swarmwalker.messages.Cell items = 1;</code>
     */
    public Builder addItems(
        int index, org.swarmwalker.messages.Cell value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(index, value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.swarmwalker.messages.Cell items = 1;</code>
     */
    public Builder addItems(
        org.swarmwalker.messages.Cell.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.swarmwalker.messages.Cell items = 1;</code>
     */
    public Builder addItems(
        int index, org.swarmwalker.messages.Cell.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.swarmwalker.messages.Cell items = 1;</code>
     */
    public Builder addAllItems(
        Iterable<? extends org.swarmwalker.messages.Cell> values) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, items_);
        onChanged();
      } else {
        itemsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .org.swarmwalker.messages.Cell items = 1;</code>
     */
    public Builder clearItems() {
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        itemsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .org.swarmwalker.messages.Cell items = 1;</code>
     */
    public Builder removeItems(int index) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.remove(index);
        onChanged();
      } else {
        itemsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .org.swarmwalker.messages.Cell items = 1;</code>
     */
    public org.swarmwalker.messages.Cell.Builder getItemsBuilder(
        int index) {
      return internalGetItemsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .org.swarmwalker.messages.Cell items = 1;</code>
     */
    public org.swarmwalker.messages.CellOrBuilder getItemsOrBuilder(
        int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);  } else {
        return itemsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .org.swarmwalker.messages.Cell items = 1;</code>
     */
    public java.util.List<? extends org.swarmwalker.messages.CellOrBuilder> 
         getItemsOrBuilderList() {
      if (itemsBuilder_ != null) {
        return itemsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(items_);
      }
    }
    /**
     * <code>repeated .org.swarmwalker.messages.Cell items = 1;</code>
     */
    public org.swarmwalker.messages.Cell.Builder addItemsBuilder() {
      return internalGetItemsFieldBuilder().addBuilder(
          org.swarmwalker.messages.Cell.getDefaultInstance());
    }
    /**
     * <code>repeated .org.swarmwalker.messages.Cell items = 1;</code>
     */
    public org.swarmwalker.messages.Cell.Builder addItemsBuilder(
        int index) {
      return internalGetItemsFieldBuilder().addBuilder(
          index, org.swarmwalker.messages.Cell.getDefaultInstance());
    }
    /**
     * <code>repeated .org.swarmwalker.messages.Cell items = 1;</code>
     */
    public java.util.List<org.swarmwalker.messages.Cell.Builder> 
         getItemsBuilderList() {
      return internalGetItemsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        org.swarmwalker.messages.Cell, org.swarmwalker.messages.Cell.Builder, org.swarmwalker.messages.CellOrBuilder> 
        internalGetItemsFieldBuilder() {
      if (itemsBuilder_ == null) {
        itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            org.swarmwalker.messages.Cell, org.swarmwalker.messages.Cell.Builder, org.swarmwalker.messages.CellOrBuilder>(
                items_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        items_ = null;
      }
      return itemsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:org.swarmwalker.messages.BiGrid)
  }

  // @@protoc_insertion_point(class_scope:org.swarmwalker.messages.BiGrid)
  private static final org.swarmwalker.messages.BiGrid DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.swarmwalker.messages.BiGrid();
  }

  public static org.swarmwalker.messages.BiGrid getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BiGrid>
      PARSER = new com.google.protobuf.AbstractParser<BiGrid>() {
    @Override
    public BiGrid parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BiGrid> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<BiGrid> getParserForType() {
    return PARSER;
  }

  @Override
  public org.swarmwalker.messages.BiGrid getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

