// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bigrid.proto
// Protobuf Java Version: 4.31.1

package org.swarmwalker.messages;

@com.google.protobuf.Generated
public interface BiGridOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.swarmwalker.messages.BiGrid)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .org.swarmwalker.messages.Cell items = 1;</code>
   */
  java.util.List<org.swarmwalker.messages.Cell> 
      getItemsList();
  /**
   * <code>repeated .org.swarmwalker.messages.Cell items = 1;</code>
   */
  org.swarmwalker.messages.Cell getItems(int index);
  /**
   * <code>repeated .org.swarmwalker.messages.Cell items = 1;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .org.swarmwalker.messages.Cell items = 1;</code>
   */
  java.util.List<? extends org.swarmwalker.messages.CellOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <code>repeated .org.swarmwalker.messages.Cell items = 1;</code>
   */
  org.swarmwalker.messages.CellOrBuilder getItemsOrBuilder(
      int index);
}
