// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bigrid.proto
// Protobuf Java Version: 4.31.1

package org.swarmwalker.messages;

@com.google.protobuf.Generated
public final class Bigrid {
  private Bigrid() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      Bigrid.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_swarmwalker_messages_BiGrid_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_swarmwalker_messages_BiGrid_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_swarmwalker_messages_Cell_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_swarmwalker_messages_Cell_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_swarmwalker_messages_Cell_DataPayload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_swarmwalker_messages_Cell_DataPayload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014bigrid.proto\022\030org.swarmwalker.messages" +
      "\032\ncore.proto\"7\n\006BiGrid\022-\n\005items\030\001 \003(\0132\036." +
      "org.swarmwalker.messages.Cell\"\334\001\n\004Cell\022\n" +
      "\n\002id\030\001 \001(\t\022,\n\004pose\030\002 \001(\0132\036.org.swarmwalk" +
      "er.messages.Pose\022,\n\004size\030\003 \001(\0132\036.org.swa" +
      "rmwalker.messages.Size\022>\n\nattributes\030\006 \003" +
      "(\0132*.org.swarmwalker.messages.Cell.DataP" +
      "ayload\032,\n\013DataPayload\022\014\n\004type\030\001 \001(\t\022\017\n\007p" +
      "ayload\030\002 \001(\tB\034\n\030org.swarmwalker.messages" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.swarmwalker.messages.Core.getDescriptor(),
        });
    internal_static_org_swarmwalker_messages_BiGrid_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_swarmwalker_messages_BiGrid_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_swarmwalker_messages_BiGrid_descriptor,
        new String[] { "Items", });
    internal_static_org_swarmwalker_messages_Cell_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_swarmwalker_messages_Cell_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_swarmwalker_messages_Cell_descriptor,
        new String[] { "Id", "Pose", "Size", "Attributes", });
    internal_static_org_swarmwalker_messages_Cell_DataPayload_descriptor =
      internal_static_org_swarmwalker_messages_Cell_descriptor.getNestedTypes().get(0);
    internal_static_org_swarmwalker_messages_Cell_DataPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_swarmwalker_messages_Cell_DataPayload_descriptor,
        new String[] { "Type", "Payload", });
    descriptor.resolveAllFeaturesImmutable();
    org.swarmwalker.messages.Core.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
