// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bigrid.proto
// Protobuf Java Version: 4.31.1

package org.swarmwalker.messages;

@com.google.protobuf.Generated
public interface CellOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.swarmwalker.messages.Cell)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>.org.swarmwalker.messages.Pose pose = 2;</code>
   * @return Whether the pose field is set.
   */
  boolean hasPose();
  /**
   * <code>.org.swarmwalker.messages.Pose pose = 2;</code>
   * @return The pose.
   */
  org.swarmwalker.messages.Pose getPose();
  /**
   * <code>.org.swarmwalker.messages.Pose pose = 2;</code>
   */
  org.swarmwalker.messages.PoseOrBuilder getPoseOrBuilder();

  /**
   * <code>.org.swarmwalker.messages.Size size = 3;</code>
   * @return Whether the size field is set.
   */
  boolean hasSize();
  /**
   * <code>.org.swarmwalker.messages.Size size = 3;</code>
   * @return The size.
   */
  org.swarmwalker.messages.Size getSize();
  /**
   * <code>.org.swarmwalker.messages.Size size = 3;</code>
   */
  org.swarmwalker.messages.SizeOrBuilder getSizeOrBuilder();

  /**
   * <code>repeated .org.swarmwalker.messages.Cell.DataPayload attributes = 6;</code>
   */
  java.util.List<org.swarmwalker.messages.Cell.DataPayload> 
      getAttributesList();
  /**
   * <code>repeated .org.swarmwalker.messages.Cell.DataPayload attributes = 6;</code>
   */
  org.swarmwalker.messages.Cell.DataPayload getAttributes(int index);
  /**
   * <code>repeated .org.swarmwalker.messages.Cell.DataPayload attributes = 6;</code>
   */
  int getAttributesCount();
  /**
   * <code>repeated .org.swarmwalker.messages.Cell.DataPayload attributes = 6;</code>
   */
  java.util.List<? extends org.swarmwalker.messages.Cell.DataPayloadOrBuilder> 
      getAttributesOrBuilderList();
  /**
   * <code>repeated .org.swarmwalker.messages.Cell.DataPayload attributes = 6;</code>
   */
  org.swarmwalker.messages.Cell.DataPayloadOrBuilder getAttributesOrBuilder(
      int index);
}
