// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bigrid.proto
// Protobuf Java Version: 4.31.1

package org.swarmwalker.messages;

/**
 * Protobuf type {@code org.swarmwalker.messages.Cell}
 */
@com.google.protobuf.Generated
public final class Cell extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:org.swarmwalker.messages.Cell)
        CellOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      Cell.class.getName());
  }
  // Use Cell.newBuilder() to construct.
  private Cell(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Cell() {
    id_ = "";
    attributes_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.swarmwalker.messages.Bigrid.internal_static_org_swarmwalker_messages_Cell_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.swarmwalker.messages.Bigrid.internal_static_org_swarmwalker_messages_Cell_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.swarmwalker.messages.Cell.class, org.swarmwalker.messages.Cell.Builder.class);
  }

  public interface DataPayloadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.swarmwalker.messages.Cell.DataPayload)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string type = 1;</code>
     * @return The type.
     */
    String getType();
    /**
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>string payload = 2;</code>
     * @return The payload.
     */
    String getPayload();
    /**
     * <code>string payload = 2;</code>
     * @return The bytes for payload.
     */
    com.google.protobuf.ByteString
        getPayloadBytes();
  }
  /**
   * Protobuf type {@code org.swarmwalker.messages.Cell.DataPayload}
   */
  public static final class DataPayload extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.swarmwalker.messages.Cell.DataPayload)
      DataPayloadOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        DataPayload.class.getName());
    }
    // Use DataPayload.newBuilder() to construct.
    private DataPayload(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private DataPayload() {
      type_ = "";
      payload_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.swarmwalker.messages.Bigrid.internal_static_org_swarmwalker_messages_Cell_DataPayload_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.swarmwalker.messages.Bigrid.internal_static_org_swarmwalker_messages_Cell_DataPayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.swarmwalker.messages.Cell.DataPayload.class, org.swarmwalker.messages.Cell.DataPayload.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object type_ = "";
    /**
     * <code>string type = 1;</code>
     * @return The type.
     */
    @Override
    public String getType() {
      Object ref = type_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    @Override
    public com.google.protobuf.ByteString
        getTypeBytes() {
      Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAYLOAD_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile Object payload_ = "";
    /**
     * <code>string payload = 2;</code>
     * @return The payload.
     */
    @Override
    public String getPayload() {
      Object ref = payload_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        payload_ = s;
        return s;
      }
    }
    /**
     * <code>string payload = 2;</code>
     * @return The bytes for payload.
     */
    @Override
    public com.google.protobuf.ByteString
        getPayloadBytes() {
      Object ref = payload_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        payload_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(type_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, type_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(payload_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, payload_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(type_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, type_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(payload_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, payload_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.swarmwalker.messages.Cell.DataPayload)) {
        return super.equals(obj);
      }
      org.swarmwalker.messages.Cell.DataPayload other = (org.swarmwalker.messages.Cell.DataPayload) obj;

      if (!getType()
          .equals(other.getType())) return false;
      if (!getPayload()
          .equals(other.getPayload())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayload().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.swarmwalker.messages.Cell.DataPayload parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.swarmwalker.messages.Cell.DataPayload parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.swarmwalker.messages.Cell.DataPayload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.swarmwalker.messages.Cell.DataPayload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.swarmwalker.messages.Cell.DataPayload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.swarmwalker.messages.Cell.DataPayload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.swarmwalker.messages.Cell.DataPayload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.swarmwalker.messages.Cell.DataPayload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.swarmwalker.messages.Cell.DataPayload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.swarmwalker.messages.Cell.DataPayload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.swarmwalker.messages.Cell.DataPayload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.swarmwalker.messages.Cell.DataPayload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.swarmwalker.messages.Cell.DataPayload prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.swarmwalker.messages.Cell.DataPayload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.swarmwalker.messages.Cell.DataPayload)
        org.swarmwalker.messages.Cell.DataPayloadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.swarmwalker.messages.Bigrid.internal_static_org_swarmwalker_messages_Cell_DataPayload_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.swarmwalker.messages.Bigrid.internal_static_org_swarmwalker_messages_Cell_DataPayload_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.swarmwalker.messages.Cell.DataPayload.class, org.swarmwalker.messages.Cell.DataPayload.Builder.class);
      }

      // Construct using org.swarmwalker.messages.Cell.DataPayload.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        type_ = "";
        payload_ = "";
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.swarmwalker.messages.Bigrid.internal_static_org_swarmwalker_messages_Cell_DataPayload_descriptor;
      }

      @Override
      public org.swarmwalker.messages.Cell.DataPayload getDefaultInstanceForType() {
        return org.swarmwalker.messages.Cell.DataPayload.getDefaultInstance();
      }

      @Override
      public org.swarmwalker.messages.Cell.DataPayload build() {
        org.swarmwalker.messages.Cell.DataPayload result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public org.swarmwalker.messages.Cell.DataPayload buildPartial() {
        org.swarmwalker.messages.Cell.DataPayload result = new org.swarmwalker.messages.Cell.DataPayload(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.swarmwalker.messages.Cell.DataPayload result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.type_ = type_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.payload_ = payload_;
        }
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.swarmwalker.messages.Cell.DataPayload) {
          return mergeFrom((org.swarmwalker.messages.Cell.DataPayload)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.swarmwalker.messages.Cell.DataPayload other) {
        if (other == org.swarmwalker.messages.Cell.DataPayload.getDefaultInstance()) return this;
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getPayload().isEmpty()) {
          payload_ = other.payload_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                type_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                payload_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object type_ = "";
      /**
       * <code>string type = 1;</code>
       * @return The type.
       */
      public String getType() {
        Object ref = type_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string type = 1;</code>
       * @return The bytes for type.
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        type_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        type_ = getDefaultInstance().getType();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string type = 1;</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        type_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private Object payload_ = "";
      /**
       * <code>string payload = 2;</code>
       * @return The payload.
       */
      public String getPayload() {
        Object ref = payload_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          payload_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string payload = 2;</code>
       * @return The bytes for payload.
       */
      public com.google.protobuf.ByteString
          getPayloadBytes() {
        Object ref = payload_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          payload_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string payload = 2;</code>
       * @param value The payload to set.
       * @return This builder for chaining.
       */
      public Builder setPayload(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        payload_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string payload = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPayload() {
        payload_ = getDefaultInstance().getPayload();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string payload = 2;</code>
       * @param value The bytes for payload to set.
       * @return This builder for chaining.
       */
      public Builder setPayloadBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        payload_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.swarmwalker.messages.Cell.DataPayload)
    }

    // @@protoc_insertion_point(class_scope:org.swarmwalker.messages.Cell.DataPayload)
    private static final org.swarmwalker.messages.Cell.DataPayload DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.swarmwalker.messages.Cell.DataPayload();
    }

    public static org.swarmwalker.messages.Cell.DataPayload getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DataPayload>
        PARSER = new com.google.protobuf.AbstractParser<DataPayload>() {
      @Override
      public DataPayload parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DataPayload> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<DataPayload> getParserForType() {
      return PARSER;
    }

    @Override
    public org.swarmwalker.messages.Cell.DataPayload getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile Object id_ = "";
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @Override
  public String getId() {
    Object ref = id_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    Object ref = id_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POSE_FIELD_NUMBER = 2;
  private org.swarmwalker.messages.Pose pose_;
  /**
   * <code>.org.swarmwalker.messages.Pose pose = 2;</code>
   * @return Whether the pose field is set.
   */
  @Override
  public boolean hasPose() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.org.swarmwalker.messages.Pose pose = 2;</code>
   * @return The pose.
   */
  @Override
  public org.swarmwalker.messages.Pose getPose() {
    return pose_ == null ? org.swarmwalker.messages.Pose.getDefaultInstance() : pose_;
  }
  /**
   * <code>.org.swarmwalker.messages.Pose pose = 2;</code>
   */
  @Override
  public org.swarmwalker.messages.PoseOrBuilder getPoseOrBuilder() {
    return pose_ == null ? org.swarmwalker.messages.Pose.getDefaultInstance() : pose_;
  }

  public static final int SIZE_FIELD_NUMBER = 3;
  private org.swarmwalker.messages.Size size_;
  /**
   * <code>.org.swarmwalker.messages.Size size = 3;</code>
   * @return Whether the size field is set.
   */
  @Override
  public boolean hasSize() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.org.swarmwalker.messages.Size size = 3;</code>
   * @return The size.
   */
  @Override
  public org.swarmwalker.messages.Size getSize() {
    return size_ == null ? org.swarmwalker.messages.Size.getDefaultInstance() : size_;
  }
  /**
   * <code>.org.swarmwalker.messages.Size size = 3;</code>
   */
  @Override
  public org.swarmwalker.messages.SizeOrBuilder getSizeOrBuilder() {
    return size_ == null ? org.swarmwalker.messages.Size.getDefaultInstance() : size_;
  }

  public static final int ATTRIBUTES_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private java.util.List<org.swarmwalker.messages.Cell.DataPayload> attributes_;
  /**
   * <code>repeated .org.swarmwalker.messages.Cell.DataPayload attributes = 6;</code>
   */
  @Override
  public java.util.List<org.swarmwalker.messages.Cell.DataPayload> getAttributesList() {
    return attributes_;
  }
  /**
   * <code>repeated .org.swarmwalker.messages.Cell.DataPayload attributes = 6;</code>
   */
  @Override
  public java.util.List<? extends org.swarmwalker.messages.Cell.DataPayloadOrBuilder> 
      getAttributesOrBuilderList() {
    return attributes_;
  }
  /**
   * <code>repeated .org.swarmwalker.messages.Cell.DataPayload attributes = 6;</code>
   */
  @Override
  public int getAttributesCount() {
    return attributes_.size();
  }
  /**
   * <code>repeated .org.swarmwalker.messages.Cell.DataPayload attributes = 6;</code>
   */
  @Override
  public org.swarmwalker.messages.Cell.DataPayload getAttributes(int index) {
    return attributes_.get(index);
  }
  /**
   * <code>repeated .org.swarmwalker.messages.Cell.DataPayload attributes = 6;</code>
   */
  @Override
  public org.swarmwalker.messages.Cell.DataPayloadOrBuilder getAttributesOrBuilder(
      int index) {
    return attributes_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, id_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getPose());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getSize());
    }
    for (int i = 0; i < attributes_.size(); i++) {
      output.writeMessage(6, attributes_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, id_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPose());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getSize());
    }
    for (int i = 0; i < attributes_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, attributes_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.swarmwalker.messages.Cell)) {
      return super.equals(obj);
    }
    org.swarmwalker.messages.Cell other = (org.swarmwalker.messages.Cell) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (hasPose() != other.hasPose()) return false;
    if (hasPose()) {
      if (!getPose()
          .equals(other.getPose())) return false;
    }
    if (hasSize() != other.hasSize()) return false;
    if (hasSize()) {
      if (!getSize()
          .equals(other.getSize())) return false;
    }
    if (!getAttributesList()
        .equals(other.getAttributesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    if (hasPose()) {
      hash = (37 * hash) + POSE_FIELD_NUMBER;
      hash = (53 * hash) + getPose().hashCode();
    }
    if (hasSize()) {
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getSize().hashCode();
    }
    if (getAttributesCount() > 0) {
      hash = (37 * hash) + ATTRIBUTES_FIELD_NUMBER;
      hash = (53 * hash) + getAttributesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.swarmwalker.messages.Cell parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.swarmwalker.messages.Cell parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.swarmwalker.messages.Cell parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.swarmwalker.messages.Cell parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.swarmwalker.messages.Cell parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.swarmwalker.messages.Cell parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.swarmwalker.messages.Cell parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.swarmwalker.messages.Cell parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.swarmwalker.messages.Cell parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.swarmwalker.messages.Cell parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.swarmwalker.messages.Cell parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.swarmwalker.messages.Cell parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.swarmwalker.messages.Cell prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.swarmwalker.messages.Cell}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.swarmwalker.messages.Cell)
      CellOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.swarmwalker.messages.Bigrid.internal_static_org_swarmwalker_messages_Cell_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.swarmwalker.messages.Bigrid.internal_static_org_swarmwalker_messages_Cell_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.swarmwalker.messages.Cell.class, org.swarmwalker.messages.Cell.Builder.class);
    }

    // Construct using org.swarmwalker.messages.Cell.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetPoseFieldBuilder();
        internalGetSizeFieldBuilder();
        internalGetAttributesFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      pose_ = null;
      if (poseBuilder_ != null) {
        poseBuilder_.dispose();
        poseBuilder_ = null;
      }
      size_ = null;
      if (sizeBuilder_ != null) {
        sizeBuilder_.dispose();
        sizeBuilder_ = null;
      }
      if (attributesBuilder_ == null) {
        attributes_ = java.util.Collections.emptyList();
      } else {
        attributes_ = null;
        attributesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.swarmwalker.messages.Bigrid.internal_static_org_swarmwalker_messages_Cell_descriptor;
    }

    @Override
    public org.swarmwalker.messages.Cell getDefaultInstanceForType() {
      return org.swarmwalker.messages.Cell.getDefaultInstance();
    }

    @Override
    public org.swarmwalker.messages.Cell build() {
      org.swarmwalker.messages.Cell result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public org.swarmwalker.messages.Cell buildPartial() {
      org.swarmwalker.messages.Cell result = new org.swarmwalker.messages.Cell(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.swarmwalker.messages.Cell result) {
      if (attributesBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          attributes_ = java.util.Collections.unmodifiableList(attributes_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.attributes_ = attributes_;
      } else {
        result.attributes_ = attributesBuilder_.build();
      }
    }

    private void buildPartial0(org.swarmwalker.messages.Cell result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.pose_ = poseBuilder_ == null
            ? pose_
            : poseBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.size_ = sizeBuilder_ == null
            ? size_
            : sizeBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.swarmwalker.messages.Cell) {
        return mergeFrom((org.swarmwalker.messages.Cell)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.swarmwalker.messages.Cell other) {
      if (other == org.swarmwalker.messages.Cell.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasPose()) {
        mergePose(other.getPose());
      }
      if (other.hasSize()) {
        mergeSize(other.getSize());
      }
      if (attributesBuilder_ == null) {
        if (!other.attributes_.isEmpty()) {
          if (attributes_.isEmpty()) {
            attributes_ = other.attributes_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureAttributesIsMutable();
            attributes_.addAll(other.attributes_);
          }
          onChanged();
        }
      } else {
        if (!other.attributes_.isEmpty()) {
          if (attributesBuilder_.isEmpty()) {
            attributesBuilder_.dispose();
            attributesBuilder_ = null;
            attributes_ = other.attributes_;
            bitField0_ = (bitField0_ & ~0x00000008);
            attributesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetAttributesFieldBuilder() : null;
          } else {
            attributesBuilder_.addAllMessages(other.attributes_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetPoseFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetSizeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 50: {
              org.swarmwalker.messages.Cell.DataPayload m =
                  input.readMessage(
                      org.swarmwalker.messages.Cell.DataPayload.parser(),
                      extensionRegistry);
              if (attributesBuilder_ == null) {
                ensureAttributesIsMutable();
                attributes_.add(m);
              } else {
                attributesBuilder_.addMessage(m);
              }
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public String getId() {
      Object ref = id_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private org.swarmwalker.messages.Pose pose_;
    private com.google.protobuf.SingleFieldBuilder<
        org.swarmwalker.messages.Pose, org.swarmwalker.messages.Pose.Builder, org.swarmwalker.messages.PoseOrBuilder> poseBuilder_;
    /**
     * <code>.org.swarmwalker.messages.Pose pose = 2;</code>
     * @return Whether the pose field is set.
     */
    public boolean hasPose() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.org.swarmwalker.messages.Pose pose = 2;</code>
     * @return The pose.
     */
    public org.swarmwalker.messages.Pose getPose() {
      if (poseBuilder_ == null) {
        return pose_ == null ? org.swarmwalker.messages.Pose.getDefaultInstance() : pose_;
      } else {
        return poseBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.swarmwalker.messages.Pose pose = 2;</code>
     */
    public Builder setPose(org.swarmwalker.messages.Pose value) {
      if (poseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pose_ = value;
      } else {
        poseBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.org.swarmwalker.messages.Pose pose = 2;</code>
     */
    public Builder setPose(
        org.swarmwalker.messages.Pose.Builder builderForValue) {
      if (poseBuilder_ == null) {
        pose_ = builderForValue.build();
      } else {
        poseBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.org.swarmwalker.messages.Pose pose = 2;</code>
     */
    public Builder mergePose(org.swarmwalker.messages.Pose value) {
      if (poseBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          pose_ != null &&
          pose_ != org.swarmwalker.messages.Pose.getDefaultInstance()) {
          getPoseBuilder().mergeFrom(value);
        } else {
          pose_ = value;
        }
      } else {
        poseBuilder_.mergeFrom(value);
      }
      if (pose_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.org.swarmwalker.messages.Pose pose = 2;</code>
     */
    public Builder clearPose() {
      bitField0_ = (bitField0_ & ~0x00000002);
      pose_ = null;
      if (poseBuilder_ != null) {
        poseBuilder_.dispose();
        poseBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.org.swarmwalker.messages.Pose pose = 2;</code>
     */
    public org.swarmwalker.messages.Pose.Builder getPoseBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetPoseFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.swarmwalker.messages.Pose pose = 2;</code>
     */
    public org.swarmwalker.messages.PoseOrBuilder getPoseOrBuilder() {
      if (poseBuilder_ != null) {
        return poseBuilder_.getMessageOrBuilder();
      } else {
        return pose_ == null ?
            org.swarmwalker.messages.Pose.getDefaultInstance() : pose_;
      }
    }
    /**
     * <code>.org.swarmwalker.messages.Pose pose = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.swarmwalker.messages.Pose, org.swarmwalker.messages.Pose.Builder, org.swarmwalker.messages.PoseOrBuilder> 
        internalGetPoseFieldBuilder() {
      if (poseBuilder_ == null) {
        poseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.swarmwalker.messages.Pose, org.swarmwalker.messages.Pose.Builder, org.swarmwalker.messages.PoseOrBuilder>(
                getPose(),
                getParentForChildren(),
                isClean());
        pose_ = null;
      }
      return poseBuilder_;
    }

    private org.swarmwalker.messages.Size size_;
    private com.google.protobuf.SingleFieldBuilder<
        org.swarmwalker.messages.Size, org.swarmwalker.messages.Size.Builder, org.swarmwalker.messages.SizeOrBuilder> sizeBuilder_;
    /**
     * <code>.org.swarmwalker.messages.Size size = 3;</code>
     * @return Whether the size field is set.
     */
    public boolean hasSize() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.org.swarmwalker.messages.Size size = 3;</code>
     * @return The size.
     */
    public org.swarmwalker.messages.Size getSize() {
      if (sizeBuilder_ == null) {
        return size_ == null ? org.swarmwalker.messages.Size.getDefaultInstance() : size_;
      } else {
        return sizeBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.swarmwalker.messages.Size size = 3;</code>
     */
    public Builder setSize(org.swarmwalker.messages.Size value) {
      if (sizeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        size_ = value;
      } else {
        sizeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.org.swarmwalker.messages.Size size = 3;</code>
     */
    public Builder setSize(
        org.swarmwalker.messages.Size.Builder builderForValue) {
      if (sizeBuilder_ == null) {
        size_ = builderForValue.build();
      } else {
        sizeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.org.swarmwalker.messages.Size size = 3;</code>
     */
    public Builder mergeSize(org.swarmwalker.messages.Size value) {
      if (sizeBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          size_ != null &&
          size_ != org.swarmwalker.messages.Size.getDefaultInstance()) {
          getSizeBuilder().mergeFrom(value);
        } else {
          size_ = value;
        }
      } else {
        sizeBuilder_.mergeFrom(value);
      }
      if (size_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.org.swarmwalker.messages.Size size = 3;</code>
     */
    public Builder clearSize() {
      bitField0_ = (bitField0_ & ~0x00000004);
      size_ = null;
      if (sizeBuilder_ != null) {
        sizeBuilder_.dispose();
        sizeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.org.swarmwalker.messages.Size size = 3;</code>
     */
    public org.swarmwalker.messages.Size.Builder getSizeBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetSizeFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.swarmwalker.messages.Size size = 3;</code>
     */
    public org.swarmwalker.messages.SizeOrBuilder getSizeOrBuilder() {
      if (sizeBuilder_ != null) {
        return sizeBuilder_.getMessageOrBuilder();
      } else {
        return size_ == null ?
            org.swarmwalker.messages.Size.getDefaultInstance() : size_;
      }
    }
    /**
     * <code>.org.swarmwalker.messages.Size size = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.swarmwalker.messages.Size, org.swarmwalker.messages.Size.Builder, org.swarmwalker.messages.SizeOrBuilder> 
        internalGetSizeFieldBuilder() {
      if (sizeBuilder_ == null) {
        sizeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.swarmwalker.messages.Size, org.swarmwalker.messages.Size.Builder, org.swarmwalker.messages.SizeOrBuilder>(
                getSize(),
                getParentForChildren(),
                isClean());
        size_ = null;
      }
      return sizeBuilder_;
    }

    private java.util.List<org.swarmwalker.messages.Cell.DataPayload> attributes_ =
      java.util.Collections.emptyList();
    private void ensureAttributesIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        attributes_ = new java.util.ArrayList<org.swarmwalker.messages.Cell.DataPayload>(attributes_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        org.swarmwalker.messages.Cell.DataPayload, org.swarmwalker.messages.Cell.DataPayload.Builder, org.swarmwalker.messages.Cell.DataPayloadOrBuilder> attributesBuilder_;

    /**
     * <code>repeated .org.swarmwalker.messages.Cell.DataPayload attributes = 6;</code>
     */
    public java.util.List<org.swarmwalker.messages.Cell.DataPayload> getAttributesList() {
      if (attributesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(attributes_);
      } else {
        return attributesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .org.swarmwalker.messages.Cell.DataPayload attributes = 6;</code>
     */
    public int getAttributesCount() {
      if (attributesBuilder_ == null) {
        return attributes_.size();
      } else {
        return attributesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .org.swarmwalker.messages.Cell.DataPayload attributes = 6;</code>
     */
    public org.swarmwalker.messages.Cell.DataPayload getAttributes(int index) {
      if (attributesBuilder_ == null) {
        return attributes_.get(index);
      } else {
        return attributesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .org.swarmwalker.messages.Cell.DataPayload attributes = 6;</code>
     */
    public Builder setAttributes(
        int index, org.swarmwalker.messages.Cell.DataPayload value) {
      if (attributesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttributesIsMutable();
        attributes_.set(index, value);
        onChanged();
      } else {
        attributesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.swarmwalker.messages.Cell.DataPayload attributes = 6;</code>
     */
    public Builder setAttributes(
        int index, org.swarmwalker.messages.Cell.DataPayload.Builder builderForValue) {
      if (attributesBuilder_ == null) {
        ensureAttributesIsMutable();
        attributes_.set(index, builderForValue.build());
        onChanged();
      } else {
        attributesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.swarmwalker.messages.Cell.DataPayload attributes = 6;</code>
     */
    public Builder addAttributes(org.swarmwalker.messages.Cell.DataPayload value) {
      if (attributesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttributesIsMutable();
        attributes_.add(value);
        onChanged();
      } else {
        attributesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .org.swarmwalker.messages.Cell.DataPayload attributes = 6;</code>
     */
    public Builder addAttributes(
        int index, org.swarmwalker.messages.Cell.DataPayload value) {
      if (attributesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttributesIsMutable();
        attributes_.add(index, value);
        onChanged();
      } else {
        attributesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.swarmwalker.messages.Cell.DataPayload attributes = 6;</code>
     */
    public Builder addAttributes(
        org.swarmwalker.messages.Cell.DataPayload.Builder builderForValue) {
      if (attributesBuilder_ == null) {
        ensureAttributesIsMutable();
        attributes_.add(builderForValue.build());
        onChanged();
      } else {
        attributesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.swarmwalker.messages.Cell.DataPayload attributes = 6;</code>
     */
    public Builder addAttributes(
        int index, org.swarmwalker.messages.Cell.DataPayload.Builder builderForValue) {
      if (attributesBuilder_ == null) {
        ensureAttributesIsMutable();
        attributes_.add(index, builderForValue.build());
        onChanged();
      } else {
        attributesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.swarmwalker.messages.Cell.DataPayload attributes = 6;</code>
     */
    public Builder addAllAttributes(
        Iterable<? extends org.swarmwalker.messages.Cell.DataPayload> values) {
      if (attributesBuilder_ == null) {
        ensureAttributesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, attributes_);
        onChanged();
      } else {
        attributesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .org.swarmwalker.messages.Cell.DataPayload attributes = 6;</code>
     */
    public Builder clearAttributes() {
      if (attributesBuilder_ == null) {
        attributes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        attributesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .org.swarmwalker.messages.Cell.DataPayload attributes = 6;</code>
     */
    public Builder removeAttributes(int index) {
      if (attributesBuilder_ == null) {
        ensureAttributesIsMutable();
        attributes_.remove(index);
        onChanged();
      } else {
        attributesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .org.swarmwalker.messages.Cell.DataPayload attributes = 6;</code>
     */
    public org.swarmwalker.messages.Cell.DataPayload.Builder getAttributesBuilder(
        int index) {
      return internalGetAttributesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .org.swarmwalker.messages.Cell.DataPayload attributes = 6;</code>
     */
    public org.swarmwalker.messages.Cell.DataPayloadOrBuilder getAttributesOrBuilder(
        int index) {
      if (attributesBuilder_ == null) {
        return attributes_.get(index);  } else {
        return attributesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .org.swarmwalker.messages.Cell.DataPayload attributes = 6;</code>
     */
    public java.util.List<? extends org.swarmwalker.messages.Cell.DataPayloadOrBuilder> 
         getAttributesOrBuilderList() {
      if (attributesBuilder_ != null) {
        return attributesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(attributes_);
      }
    }
    /**
     * <code>repeated .org.swarmwalker.messages.Cell.DataPayload attributes = 6;</code>
     */
    public org.swarmwalker.messages.Cell.DataPayload.Builder addAttributesBuilder() {
      return internalGetAttributesFieldBuilder().addBuilder(
          org.swarmwalker.messages.Cell.DataPayload.getDefaultInstance());
    }
    /**
     * <code>repeated .org.swarmwalker.messages.Cell.DataPayload attributes = 6;</code>
     */
    public org.swarmwalker.messages.Cell.DataPayload.Builder addAttributesBuilder(
        int index) {
      return internalGetAttributesFieldBuilder().addBuilder(
          index, org.swarmwalker.messages.Cell.DataPayload.getDefaultInstance());
    }
    /**
     * <code>repeated .org.swarmwalker.messages.Cell.DataPayload attributes = 6;</code>
     */
    public java.util.List<org.swarmwalker.messages.Cell.DataPayload.Builder> 
         getAttributesBuilderList() {
      return internalGetAttributesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        org.swarmwalker.messages.Cell.DataPayload, org.swarmwalker.messages.Cell.DataPayload.Builder, org.swarmwalker.messages.Cell.DataPayloadOrBuilder> 
        internalGetAttributesFieldBuilder() {
      if (attributesBuilder_ == null) {
        attributesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            org.swarmwalker.messages.Cell.DataPayload, org.swarmwalker.messages.Cell.DataPayload.Builder, org.swarmwalker.messages.Cell.DataPayloadOrBuilder>(
                attributes_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        attributes_ = null;
      }
      return attributesBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:org.swarmwalker.messages.Cell)
  }

  // @@protoc_insertion_point(class_scope:org.swarmwalker.messages.Cell)
  private static final org.swarmwalker.messages.Cell DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.swarmwalker.messages.Cell();
  }

  public static org.swarmwalker.messages.Cell getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Cell>
      PARSER = new com.google.protobuf.AbstractParser<Cell>() {
    @Override
    public Cell parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Cell> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Cell> getParserForType() {
    return PARSER;
  }

  @Override
  public org.swarmwalker.messages.Cell getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

