// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: core.proto
// Protobuf Java Version: 4.31.1

package org.swarmwalker.messages;

@com.google.protobuf.Generated
public final class Core {
  private Core() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      Core.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_swarmwalker_messages_Size_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_swarmwalker_messages_Size_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_swarmwalker_messages_Pose_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_swarmwalker_messages_Pose_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\ncore.proto\022\030org.swarmwalker.messages\"c" +
      "\n\004Size\022,\n\004unit\030\001 \001(\0162\036.org.swarmwalker.m" +
      "essages.Unit\022\r\n\005width\030\002 \001(\002\022\016\n\006length\030\003 " +
      "\001(\002\022\016\n\006height\030\004 \001(\002\"`\n\004Pose\022,\n\004type\030\001 \001(" +
      "\0162\036.org.swarmwalker.messages.Type\022\t\n\001x\030\002" +
      " \001(\002\022\t\n\001y\030\003 \001(\002\022\t\n\001z\030\004 \001(\002\022\t\n\001w\030\005 \001(\002*1\n" +
      "\004Unit\022\016\n\nMillimeter\020\000\022\016\n\nCentimeter\020\001\022\t\n" +
      "\005Meter\020\002*%\n\004Type\022\r\n\tCartesian\020\000\022\016\n\nQuate" +
      "rnion\020\001B\034\n\030org.swarmwalker.messagesP\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_swarmwalker_messages_Size_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_swarmwalker_messages_Size_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_swarmwalker_messages_Size_descriptor,
        new String[] { "Unit", "Width", "Length", "Height", });
    internal_static_org_swarmwalker_messages_Pose_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_swarmwalker_messages_Pose_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_swarmwalker_messages_Pose_descriptor,
        new String[] { "Type", "X", "Y", "Z", "W", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
