// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: core.proto
// Protobuf Java Version: 4.31.1

package org.swarmwalker.messages;

@com.google.protobuf.Generated
public interface PoseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.swarmwalker.messages.Pose)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.swarmwalker.messages.Type type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.org.swarmwalker.messages.Type type = 1;</code>
   * @return The type.
   */
  org.swarmwalker.messages.Type getType();

  /**
   * <code>float x = 2;</code>
   * @return The x.
   */
  float getX();

  /**
   * <code>float y = 3;</code>
   * @return The y.
   */
  float getY();

  /**
   * <code>float z = 4;</code>
   * @return The z.
   */
  float getZ();

  /**
   * <code>float w = 5;</code>
   * @return The w.
   */
  float getW();
}
