// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: core.proto
// Protobuf Java Version: 4.31.1

package org.swarmwalker.messages;

@com.google.protobuf.Generated
public interface SizeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.swarmwalker.messages.Size)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.swarmwalker.messages.Unit unit = 1;</code>
   * @return The enum numeric value on the wire for unit.
   */
  int getUnitValue();
  /**
   * <code>.org.swarmwalker.messages.Unit unit = 1;</code>
   * @return The unit.
   */
  Unit getUnit();

  /**
   * <code>float width = 2;</code>
   * @return The width.
   */
  float getWidth();

  /**
   * <code>float length = 3;</code>
   * @return The length.
   */
  float getLength();

  /**
   * <code>float height = 4;</code>
   * @return The height.
   */
  float getHeight();
}
