// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: core.proto
// Protobuf Java Version: 4.31.1

package org.swarmwalker.messages;

/**
 * Protobuf type {@code org.swarmwalker.messages.Size}
 */
@com.google.protobuf.Generated
public final class Size extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:org.swarmwalker.messages.Size)
        SizeOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      Size.class.getName());
  }
  // Use Size.newBuilder() to construct.
  private Size(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Size() {
    unit_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.swarmwalker.messages.Core.internal_static_org_swarmwalker_messages_Size_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.swarmwalker.messages.Core.internal_static_org_swarmwalker_messages_Size_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.swarmwalker.messages.Size.class, org.swarmwalker.messages.Size.Builder.class);
  }

  public static final int UNIT_FIELD_NUMBER = 1;
  private int unit_ = 0;
  /**
   * <code>.org.swarmwalker.messages.Unit unit = 1;</code>
   * @return The enum numeric value on the wire for unit.
   */
  @Override public int getUnitValue() {
    return unit_;
  }
  /**
   * <code>.org.swarmwalker.messages.Unit unit = 1;</code>
   * @return The unit.
   */
  @Override public org.swarmwalker.messages.Unit getUnit() {
    org.swarmwalker.messages.Unit result = org.swarmwalker.messages.Unit.forNumber(unit_);
    return result == null ? org.swarmwalker.messages.Unit.UNRECOGNIZED : result;
  }

  public static final int WIDTH_FIELD_NUMBER = 2;
  private float width_ = 0F;
  /**
   * <code>float width = 2;</code>
   * @return The width.
   */
  @Override
  public float getWidth() {
    return width_;
  }

  public static final int LENGTH_FIELD_NUMBER = 3;
  private float length_ = 0F;
  /**
   * <code>float length = 3;</code>
   * @return The length.
   */
  @Override
  public float getLength() {
    return length_;
  }

  public static final int HEIGHT_FIELD_NUMBER = 4;
  private float height_ = 0F;
  /**
   * <code>float height = 4;</code>
   * @return The height.
   */
  @Override
  public float getHeight() {
    return height_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (unit_ != org.swarmwalker.messages.Unit.Millimeter.getNumber()) {
      output.writeEnum(1, unit_);
    }
    if (Float.floatToRawIntBits(width_) != 0) {
      output.writeFloat(2, width_);
    }
    if (Float.floatToRawIntBits(length_) != 0) {
      output.writeFloat(3, length_);
    }
    if (Float.floatToRawIntBits(height_) != 0) {
      output.writeFloat(4, height_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (unit_ != org.swarmwalker.messages.Unit.Millimeter.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, unit_);
    }
    if (Float.floatToRawIntBits(width_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, width_);
    }
    if (Float.floatToRawIntBits(length_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, length_);
    }
    if (Float.floatToRawIntBits(height_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(4, height_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.swarmwalker.messages.Size)) {
      return super.equals(obj);
    }
    org.swarmwalker.messages.Size other = (org.swarmwalker.messages.Size) obj;

    if (unit_ != other.unit_) return false;
    if (Float.floatToIntBits(getWidth())
        != Float.floatToIntBits(
            other.getWidth())) return false;
    if (Float.floatToIntBits(getLength())
        != Float.floatToIntBits(
            other.getLength())) return false;
    if (Float.floatToIntBits(getHeight())
        != Float.floatToIntBits(
            other.getHeight())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + UNIT_FIELD_NUMBER;
    hash = (53 * hash) + unit_;
    hash = (37 * hash) + WIDTH_FIELD_NUMBER;
    hash = (53 * hash) + Float.floatToIntBits(
        getWidth());
    hash = (37 * hash) + LENGTH_FIELD_NUMBER;
    hash = (53 * hash) + Float.floatToIntBits(
        getLength());
    hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + Float.floatToIntBits(
        getHeight());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.swarmwalker.messages.Size parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.swarmwalker.messages.Size parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.swarmwalker.messages.Size parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.swarmwalker.messages.Size parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.swarmwalker.messages.Size parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.swarmwalker.messages.Size parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.swarmwalker.messages.Size parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.swarmwalker.messages.Size parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.swarmwalker.messages.Size parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.swarmwalker.messages.Size parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.swarmwalker.messages.Size parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.swarmwalker.messages.Size parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.swarmwalker.messages.Size prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.swarmwalker.messages.Size}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.swarmwalker.messages.Size)
      SizeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.swarmwalker.messages.Core.internal_static_org_swarmwalker_messages_Size_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.swarmwalker.messages.Core.internal_static_org_swarmwalker_messages_Size_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.swarmwalker.messages.Size.class, org.swarmwalker.messages.Size.Builder.class);
    }

    // Construct using org.swarmwalker.messages.Size.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      unit_ = 0;
      width_ = 0F;
      length_ = 0F;
      height_ = 0F;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.swarmwalker.messages.Core.internal_static_org_swarmwalker_messages_Size_descriptor;
    }

    @Override
    public org.swarmwalker.messages.Size getDefaultInstanceForType() {
      return org.swarmwalker.messages.Size.getDefaultInstance();
    }

    @Override
    public org.swarmwalker.messages.Size build() {
      org.swarmwalker.messages.Size result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public org.swarmwalker.messages.Size buildPartial() {
      org.swarmwalker.messages.Size result = new org.swarmwalker.messages.Size(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.swarmwalker.messages.Size result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.unit_ = unit_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.width_ = width_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.length_ = length_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.height_ = height_;
      }
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.swarmwalker.messages.Size) {
        return mergeFrom((org.swarmwalker.messages.Size)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.swarmwalker.messages.Size other) {
      if (other == org.swarmwalker.messages.Size.getDefaultInstance()) return this;
      if (other.unit_ != 0) {
        setUnitValue(other.getUnitValue());
      }
      if (Float.floatToRawIntBits(other.getWidth()) != 0) {
        setWidth(other.getWidth());
      }
      if (Float.floatToRawIntBits(other.getLength()) != 0) {
        setLength(other.getLength());
      }
      if (Float.floatToRawIntBits(other.getHeight()) != 0) {
        setHeight(other.getHeight());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              unit_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 21: {
              width_ = input.readFloat();
              bitField0_ |= 0x00000002;
              break;
            } // case 21
            case 29: {
              length_ = input.readFloat();
              bitField0_ |= 0x00000004;
              break;
            } // case 29
            case 37: {
              height_ = input.readFloat();
              bitField0_ |= 0x00000008;
              break;
            } // case 37
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int unit_ = 0;
    /**
     * <code>.org.swarmwalker.messages.Unit unit = 1;</code>
     * @return The enum numeric value on the wire for unit.
     */
    @Override public int getUnitValue() {
      return unit_;
    }
    /**
     * <code>.org.swarmwalker.messages.Unit unit = 1;</code>
     * @param value The enum numeric value on the wire for unit to set.
     * @return This builder for chaining.
     */
    public Builder setUnitValue(int value) {
      unit_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.org.swarmwalker.messages.Unit unit = 1;</code>
     * @return The unit.
     */
    @Override
    public org.swarmwalker.messages.Unit getUnit() {
      org.swarmwalker.messages.Unit result = org.swarmwalker.messages.Unit.forNumber(unit_);
      return result == null ? org.swarmwalker.messages.Unit.UNRECOGNIZED : result;
    }
    /**
     * <code>.org.swarmwalker.messages.Unit unit = 1;</code>
     * @param value The unit to set.
     * @return This builder for chaining.
     */
    public Builder setUnit(org.swarmwalker.messages.Unit value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000001;
      unit_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.org.swarmwalker.messages.Unit unit = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUnit() {
      bitField0_ = (bitField0_ & ~0x00000001);
      unit_ = 0;
      onChanged();
      return this;
    }

    private float width_ ;
    /**
     * <code>float width = 2;</code>
     * @return The width.
     */
    @Override
    public float getWidth() {
      return width_;
    }
    /**
     * <code>float width = 2;</code>
     * @param value The width to set.
     * @return This builder for chaining.
     */
    public Builder setWidth(float value) {

      width_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>float width = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearWidth() {
      bitField0_ = (bitField0_ & ~0x00000002);
      width_ = 0F;
      onChanged();
      return this;
    }

    private float length_ ;
    /**
     * <code>float length = 3;</code>
     * @return The length.
     */
    @Override
    public float getLength() {
      return length_;
    }
    /**
     * <code>float length = 3;</code>
     * @param value The length to set.
     * @return This builder for chaining.
     */
    public Builder setLength(float value) {

      length_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>float length = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLength() {
      bitField0_ = (bitField0_ & ~0x00000004);
      length_ = 0F;
      onChanged();
      return this;
    }

    private float height_ ;
    /**
     * <code>float height = 4;</code>
     * @return The height.
     */
    @Override
    public float getHeight() {
      return height_;
    }
    /**
     * <code>float height = 4;</code>
     * @param value The height to set.
     * @return This builder for chaining.
     */
    public Builder setHeight(float value) {

      height_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>float height = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearHeight() {
      bitField0_ = (bitField0_ & ~0x00000008);
      height_ = 0F;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:org.swarmwalker.messages.Size)
  }

  // @@protoc_insertion_point(class_scope:org.swarmwalker.messages.Size)
  private static final org.swarmwalker.messages.Size DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.swarmwalker.messages.Size();
  }

  public static org.swarmwalker.messages.Size getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Size>
      PARSER = new com.google.protobuf.AbstractParser<Size>() {
    @Override
    public Size parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Size> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Size> getParserForType() {
    return PARSER;
  }

  @Override
  public org.swarmwalker.messages.Size getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

