// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: core.proto
// Protobuf Java Version: 4.31.1

package org.swarmwalker.messages;

/**
 * Protobuf enum {@code org.swarmwalker.messages.Unit}
 */
@com.google.protobuf.Generated
public enum Unit
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>Millimeter = 0;</code>
   */
  Millimeter(0),
  /**
   * <code>Centimeter = 1;</code>
   */
  Centimeter(1),
  /**
   * <code>Meter = 2;</code>
   */
  Meter(2),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      Unit.class.getName());
  }
  /**
   * <code>Millimeter = 0;</code>
   */
  public static final int Millimeter_VALUE = 0;
  /**
   * <code>Centimeter = 1;</code>
   */
  public static final int Centimeter_VALUE = 1;
  /**
   * <code>Meter = 2;</code>
   */
  public static final int Meter_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static Unit valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static Unit forNumber(int value) {
    switch (value) {
      case 0: return Millimeter;
      case 1: return Centimeter;
      case 2: return Meter;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Unit>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Unit> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Unit>() {
          public Unit findValueByNumber(int number) {
            return Unit.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return Core.getDescriptor().getEnumTypes().get(0);
  }

  private static final Unit[] VALUES = values();

  public static Unit valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Unit(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:org.swarmwalker.messages.Unit)
}

